cask "font-iosevka-comfy" do
  version "0.1.0"
  sha256 "2c6843d48838227e58861be4b7f75f2b77116b99a1ab82707f42b17167549dd0"
  url "https://github.com/ingorichter/homebrew-iosevka-comfy/releases/download/#{version}/iosevka-comfy.zip"
  name "Iosevka Comfy"
  homepage "https://github.com/protesilaos/iosevka-comfy"

  livecheck do
    url :url
    strategy :github_latest
  end

  font "iosevka-comfy-bold.ttf"
  font "iosevka-comfy-bolditalic.ttf"
  font "iosevka-comfy-duo-bold.ttf"
  font "iosevka-comfy-duo-bolditalic.ttf"
  font "iosevka-comfy-duo-extrabold.ttf"
  font "iosevka-comfy-duo-extrabolditalic.ttf"
  font "iosevka-comfy-duo-italic.ttf"
  font "iosevka-comfy-duo-light.ttf"
  font "iosevka-comfy-duo-lightitalic.ttf"
  font "iosevka-comfy-duo-regular.ttf"
  font "iosevka-comfy-duo-semilight.ttf"
  font "iosevka-comfy-duo-semilightitalic.ttf"
  font "iosevka-comfy-extrabold.ttf"
  font "iosevka-comfy-extrabolditalic.ttf"
  font "iosevka-comfy-fixed-bold.ttf"
  font "iosevka-comfy-fixed-bolditalic.ttf"
  font "iosevka-comfy-fixed-extrabold.ttf"
  font "iosevka-comfy-fixed-extrabolditalic.ttf"
  font "iosevka-comfy-fixed-italic.ttf"
  font "iosevka-comfy-fixed-light.ttf"
  font "iosevka-comfy-fixed-lightitalic.ttf"
  font "iosevka-comfy-fixed-regular.ttf"
  font "iosevka-comfy-fixed-semilight.ttf"
  font "iosevka-comfy-fixed-semilightitalic.ttf"
  font "iosevka-comfy-italic.ttf"
  font "iosevka-comfy-light.ttf"
  font "iosevka-comfy-lightitalic.ttf"
  font "iosevka-comfy-regular.ttf"
  font "iosevka-comfy-semilight.ttf"
  font "iosevka-comfy-semilightitalic.ttf"
  font "iosevka-comfy-wide-bold.ttf"
  font "iosevka-comfy-wide-bolditalic.ttf"
  font "iosevka-comfy-wide-extrabold.ttf"
  font "iosevka-comfy-wide-extrabolditalic.ttf"
  font "iosevka-comfy-wide-fixed-bold.ttf"
  font "iosevka-comfy-wide-fixed-bolditalic.ttf"
  font "iosevka-comfy-wide-fixed-extrabold.ttf"
  font "iosevka-comfy-wide-fixed-extrabolditalic.ttf"
  font "iosevka-comfy-wide-fixed-italic.ttf"
  font "iosevka-comfy-wide-fixed-light.ttf"
  font "iosevka-comfy-wide-fixed-lightitalic.ttf"
  font "iosevka-comfy-wide-fixed-regular.ttf"
  font "iosevka-comfy-wide-fixed-semilight.ttf"
  font "iosevka-comfy-wide-fixed-semilightitalic.ttf"
  font "iosevka-comfy-wide-italic.ttf"
  font "iosevka-comfy-wide-light.ttf"
  font "iosevka-comfy-wide-lightitalic.ttf"
  font "iosevka-comfy-wide-regular.ttf"
  font "iosevka-comfy-wide-semilight.ttf"
  font "iosevka-comfy-wide-semilightitalic.ttf"
end